openapi: 3.0.3
info:
  title: auth.hasanjoldic.com API
  version: v1
servers:
  - url: https://auth.hasanjoldic.com/api/v1
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: office@hasanjoldic.com
                password:
                  type: string
                  minLength: 8
                  example: mystrongpassword
              required:
                - email
                - password
      responses:
        200:
          description: 200 Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                required:
                  - token
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
components:
  schemas:
    Error:
      type: object
      properties:
        statusCode:
          type: integer
          minimum: 400
          maximum: 599
          example: 404
        error:
          type: string
          description: HTTP error message
          example: Not found
        message:
          type: string
          description: Detailed error message
          example: Cannot GET /api/v1/files
      required:
        - statusCode
          